Feature: Refine filters
Hong-Kong-Districts-Info/hktrafficcollisions pull request #14
Opened 2021-07-11 03:14 UTC by KHwong12

# Summary
This branch refines the filter panel by using alternative buttons and reorder the filters.

# Changes
The changes made in this PR are:
1. Change UI of severity type filter (`severity_filter`) to multiple checkboxes

    The old filter is a drop-down list. Now replaced with a filter of multiple checkboxes.

    ![](https://user-images.githubusercontent.com/29334677/125181402-e8fdf180-e236-11eb-828c-e743e7489840.png)

1. Add a filter of casualty type

    This filter filters the dataset by the types of casualties involved in each accident, including **Pedestrian**, **Driver** and **Passenger**. Note that selecting multiple inputs means filtering accidents including ANY of the selected classes, instead of includes ALL of the selected classes. For example, when the users choose both **Pedestrian** and **Driver** in this filter, collisions which 1. casualties include only pedestrians; 2. casualties include only drivers and 3. casualties include both pedestrians and drivers will be displayed on the map. 

    ![](https://user-images.githubusercontent.com/29334677/125181494-eb148000-e237-11eb-8183-6cf526367b9b.png)   

1. Remove existing filter of whether pedestrians are involved in the accident

    This filter overlaps with the collision type filter and the new casualty type filter.

1. Reorder filters

    Filters are reordered to the following order (filter name in `ui.R`):

    1. Date range (`date_filter`)
    2. Severity (`severity_filter`)
    3. Collision type (`collision_type_filter`)
    4. Casualty role (`casualty_filter`)
    5. Vehicles involved (`vehicle_class_filter`)
    6. Number of casualties (`n_causality_filter`)
    
    The order is referenced from [Crash Map](https://www.crashmap.co.uk/Search).

    ![](https://user-images.githubusercontent.com/29334677/125181552-70983000-e238-11eb-8789-ac96007508d7.png)

***

# Check
- [ ] The travis.ci and R CMD checks pass.

***

## Note

- We may discuss ways to enhance and simplify the UI in future development. The filter panel looks a bit long to me now. It takes some time for new users to understand what each filter is doing. 😐

2021-07-11 18:27 UTC, KHwong12 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Map Viewer - Start with Pop-up Preview & Full Details Page](https://trello.com/c/tSgikljF/88-map-viewer-start-with-pop-up-preview-full-details-page)

2021-07-26 22:09 UTC, avisionh requested changes
Wonderful stuff! I've made a few minor comments about using consistent assignment operators and improving the grammar.

There are two other things, outlined below, however, they can be dealt with in a separate PR, which is what you mentioned..
1. Great that you can drag and drop the **Filter Panel** (was pleasantly surprised when I did this by accident). However, it seems to also overflow onto the other parts of the dashboard when you scroll down. (Screenshot provided below).
2. The *No. of casualties* slider doesn't seem to update in accordance with the filters selected. Is this expected behaviour?

![image](https://user-images.githubusercontent.com/25527485/127065634-2c3419d6-890e-4edf-a6ae-caf53c9d30ec.png)

2021-07-26 22:09 UTC, avisionh commented on inst/app/modules/main_map.R
>  hk_vehicles_involved = hk_vehicles %>%
Apply consistent assignment operator.
```suggestion
hk_vehicles_involved <- hk_vehicles %>%
```

2021-07-26 22:09 UTC, avisionh commented on inst/app/ui.R
> +                            `Slight <i style="color:#F1701E;" class="fas fa-user-injured"></i>` = "Slight"),
Nice use of icons here.

2021-07-26 22:09 UTC, avisionh commented on inst/app/ui.R
> +                step = 1
Should the range of 1 to 77 update according to the filters chosen by the user? If yes, it didn't work when I tried.

2021-07-28 12:16 UTC, KHwong12 commented
Thanks for such a detailed review! Let me address your concerns before looking into the suggestions.

> However, it seems to also overflow onto the other parts of the dashboard when you scroll down. (Screenshot provided below).

You took the words out of my mouth. I also find the panel is now too long and kind of weird. I looked for ways to collapse the panel before (like [this SO question](https://stackoverflow.com/questions/35175167/collapse-absolutepanel-in-shiny)) and would like to give it a go in future development.

Another way we could do is to remove the number of filters? Would it be better to "restrict" the number of choices for users?

> The _No. of casualties_ slider doesn't seem to update in accordance with the filters selected. Is this expected behaviour?

Yep, that's expected behaviour. Like the collision type filter and collision severity filter, the choices available are independent of the users' current selection. It is based on the **whole** `hk_accdients` dataset, where the min and max number of causalities are 1 and 77.

IMO continuously updating the available choices in the filter may be a little bit confusing. We may add some basic summary statistics below the map if the user would like to get the min/max number of causalities in his/her current selection...? 🤔

2021-08-06 22:06 UTC, avisionh commented
Thanks for making the tweaks!

> Thanks for such a detailed review! Let me address your concerns before looking into the suggestions.
> 
> > However, it seems to also overflow onto the other parts of the dashboard when you scroll down. (Screenshot provided below).
> 
> You took the words out of my mouth. I also find the panel is now too long and kind of weird. I looked for ways to collapse the panel before (like [this SO question](https://stackoverflow.com/questions/35175167/collapse-absolutepanel-in-shiny)) and would like to give it a go in future development.
> 
> Another way we could do is to remove the number of filters? Would it be better to "restrict" the number of choices for users?

Removing the filters is an interesting suggestion. I do feel there are quite a lot of filters that, from user perspective, can seem overwhelming initially as someone who is not familiar with traffic collisions data. Nevertheless, I remember that the users being targeted with this dashboard are more technical from the angle of knowing more about traffic collisions, so they will benefit from the extra granular detail they can derive from tweaking these filters. In that regard, I think keeping the filters as is would be sufficient. 

I definitely feel being able to collapse the panel will be a great addition in a separate PR.

> 
> > The _No. of casualties_ slider doesn't seem to update in accordance with the filters selected. Is this expected behaviour?
> 
> Yep, that's expected behaviour. Like the collision type filter and collision severity filter, the choices available are independent of users' current selection. It is based on the **whole** `hk_accdients` dataset, where the min and max number of causalities are 1 and 77.
> 
> IMO continuously updating the available choices in the filter may be a little bit confusing. We may add some basic summary statistics below the map if the user would like to get the min/max number of causalities in his/her current selection...? 🤔

Thanks for the explanation, makes sense and I agree with your point about why continuously updating the available choices can be confusing. Filling out those plots and including more summary statistics will be a really great addition.

2021-08-06 22:06 UTC, avisionh approved these changes

2021-08-15 19:34 UTC, merged